trigger:
  - main
  - refs/tags/*

pr:
  - main

pool:
    vmImage: 'windows-2019'

variables:
  buildConfiguration: 'Release'
  sdkDirectory: 'sdk/dotnet'
  sdkSolution: 'sdk/dotnet/Datasync.Framework.sln'
  BASE_VERSION: 5.0.0
  PREVIEW_LABEL: 'preview'
  BUILD_NUMBER: $[counter(format('{0}_{1}_{2}', variables['BASE_VERSION'], variables['PREVIEW_LABEL'], variables['Build.SourceBranch']), 1)]
  NUGET_VERSION: $[format('{0}-{1}.{2}', variables['BASE_VERSION'], variables['PREVIEW_LABEL'], variables['BUILD_NUMBER'])]

jobs:
  - job: buildsdk
    displayName: 'Build .NET SDK'
    steps:
      - task: UseDotNet@2
        displayName: 'Setup .NET Core SDK'
        inputs:
          version: '5.0.x'
          performMultiLevelLookup: true
          
      - task: DotNetCoreCLI@2
        displayName: 'Restore Packages'
        inputs:
          command: restore
          projects: '$(sdkDirectory)/**/*.csproj'
          workingDirectory: $(sdkDirectory)
          verbosityRestore: 'normal'
      
      - task: MSBuild@1
        displayName: 'Build SDK'
        inputs:
          configuration: $(buildConfiguration)
          solution: $(sdkSolution)
          msbuildArguments: '-t:Build -p:PackageVersion=$(NUGET_VERSION)'

      - task: DotNetCoreCLI@2
        displayName: 'Unit Tests'
        inputs:
          command: test
          arguments: '--no-build --no-restore'
          configuration: $(buildConfiguration)
          workingDirectory: $(sdkDirectory)
          
