trigger:
  - main
  - refs/tags/*

pr:
  - main

pool:
  vmImage: 'windows-2019'

variables:
  buildConfiguration: 'Release'
  netSdkPath: 'sdk/dotnet'
  netSdkSolution: '$(netSdkPath)/Datasync.Framework.sln'
  BASE_VERSION: 5.0.0
  PREVIEW_LABEL: 'preview'
  BUILD_NUMBER: $[counter(format('{0}_{1}_{2}', variables['BASE_VERSION'], variables['PREVIEW_LABEL'], variables['Build.SourceBranch']), 1)]
  NUGET_VERSION: $[format('{0}-{1}.{2}', variables['BASE_VERSION'], variables['PREVIEW_LABEL'], variables['BUILD_NUMBER'])]

resources:
  repositories:
    - repository: internal-templates
      type: github
      name: xamarin/yaml-templates
      endpoint: xamarin

stages:
  - stage: build
    displayName: Build SDK
    jobs:
      - job: buildnetsdk
        displayName: Build .NET SDK
        steps:
          - template: .ci/prebuild.yml

          - task: MSBuild@1
            displayName: 'Build SDK'
            inputs:
              configuration: $(buildConfiguration)
              solution: $(netSdkSolution)
              msBuildArguments: '/nologo /t:Restore;Build;Pack /p:PackageVersion=$(NUGET_VERSION) /p:Version=$(BASE_VERSION) /bl /clp:DisableConsoleColor;Verbosity:normal;PerformanceSummary /fl'

          - task: VSTest@2
            displayName: 'Run Unit Tests'
            inputs:
              testAssemblyVer2: |
                **\Microsoft.*.Test.dll
                !**\obj\**
                !**\bin\**\ref\**
              searchFolder: $(netSdkPath)
              codeCoverageEnabled: true
              diagnosticsEnabled: true
              runTestsInIsolation: true
              configuration: $(buildConfiguration)

          - template: .ci/postbuild.yml
            parameters:
              sourceDirectory: '$(netSdkPath)/src'
              buildConfiguration: '$(buildConfiguration)'

      - job: buildnettemplate
        displayName: Build .NET Core Template
        steps:
          - template: .ci/prebuild.yml

          - pwsh: |
              dotnet pack DatasyncTemplates.csproj --configuration $(buildConfiguration) /p:PackageVersion=$(NUGET_VERSION)
            displayName: Build Template
            workingDirectory: '$(netSdkPath)/templates'

          - template: .ci/postbuild.yml
            parameters:
              sourceDirectory: '$(netSdkPath)/templates'
              buildConfiguration: '$(buildConfiguration)'

  - stage: sign
    displayName: Sign SDK
    dependsOn: [ 'build' ]
    jobs:
      - template: sign-artifacts/jobs/v2.yml@internal-templates
        parameters:
          codeSignOverride: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
  