trigger:
  - main
  - refs/tags/*

pr:
  - main

pool:
    vmImage: 'windows-2019'

variables:
  buildConfiguration: 'Release'
  sdkDirectory: 'sdk/dotnet'
  sdkSolution: 'sdk/dotnet/Datasync.Framework.sln'
  BASE_VERSION: 5.0.0
  PREVIEW_LABEL: 'preview'
  BUILD_NUMBER: $[counter(format('{0}_{1}_{2}', variables['BASE_VERSION'], variables['PREVIEW_LABEL'], variables['Build.SourceBranch']), 1)]
  NUGET_VERSION: $[format('{0}-{1}.{2}', variables['BASE_VERSION'], variables['PREVIEW_LABEL'], variables['BUILD_NUMBER'])]

jobs:
  - job: buildsdk
    displayName: 'Build .NET SDK'
    steps:
      - task: NuGetToolInstaller@1

      - task: NuGetCommand@2
        inputs:
          restoreSolution: $(sdkSolution)
      
      - task: MSBuild@1
        inputs:
          configuration: $(buildConfiguration)
          solution: $(sdkSolution)
          msbuildArguments: '-t:Build -p:PackageVersion=$(NUGET_VERSION)'

      - task: DotNetCoreCLI@2
        inputs:
          command: test
          configuration: $(buildConfiguration)
          workingDirectory: $(sdkDirectory)
          nobuild: true

      - task: PublishTestResults@2
        displayName: 'Publish the test results'
        inputs:
          testResultsFormat: xUnit
          testResultsFiles: '$(sdkDirectory)/output/**/*TestResults.xml'
          testRunTitle: 'xUnit test results for $(System.JobName)'



