trigger:
  - main
  - refs/tags/*

pr:
  - main

pool:
    vmImage: 'windows-2019'

variables:
  AREA_PATH: 'DevDiv\Xamarin SDK'
  sdkPath: 'sdk/dotnet'
  templatePath: 'templates/dotnet'
  buildConfiguration: 'Release'
  BASE_VERSION: 5.0.0
  PREVIEW_LABEL: 'preview'
  BUILD_NUMBER: $[counter(format('{0}_{1}_{2}', variables['BASE_VERSION'], variables['PREVIEW_LABEL'], variables['Build.SourceBranch']), 1)]
  NUGET_VERSION: $[format('{0}-{1}.{2}', variables['BASE_VERSION'], variables['PREVIEW_LABEL'], variables['BUILD_NUMBER'])]

resources:
  repositories:
    - repository: internal-templates
      type: github
      name: xamarin/yaml-templates
      endpoint: xamarin
    - repository: components
      type: github
      name: xamarin/XamarinComponents
      endpoint: xamarin

stages:
  - stage: buildsdk
    displayName: Build .NET SDK
    dependsOn: []
    jobs:
      - template: .ci/build.yml@components
        parameters:
          publishJob: windows
          # Disable building on mac and linux - we only build on Windows
          macosImage: ''
          linuxImage: ''
          windowsImage: 'windows-2019'
          # Our stuff is in sdk/dotnet, so need to adjust the artifacts-path
          artifactsPath: '$(sdkPath)/output'
          areaPath: $(AREA_PATH)
          cakeFile: '$(sdkPath)/build.cake'
          validPackagePrefixes:
            - Microsoft.AspNetCore.Datasync
            - Microsoft.Datasync.Client
          preBuildSteps:
            - pwsh: |
                $pr = "pr." + $env:SYSTEM_PULLREQUEST_PULLREQUESTNUMBER
                $nuget = $env:BASE_VERSION + "-" + $pr + "." + $env:BUILD_NUMBER
                Write-Host "Preview label: $pr"
                Write-Host "NuGet version: $nuget"
                Write-Host "##vso[task.setvariable variable=PREVIEW_LABEL]$pr"
                Write-Host "##vso[task.setvariable variable=NUGET_VERSION]$nuget"
              displayName: Use a special preview label for PRs
              condition: eq(variables['Build.Reason'], 'PullRequest')
            - pwsh: |
                $tagVersion = $env:BUILD_SOURCEBRANCHNAME
                Write-Host "Tag version: $tagVersion"
                Write-Host "##vso[task.setvariable variable=NUGET_VERSION]$tagVersion"
              displayName: Override version for tags
              condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
            - pwsh: |
                Write-Host "##vso[build.updatebuildnumber]$env:NUGET_VERSION"
              displayName: Update the build number with a more readable one

      - job: buildtemplate
        displayName: 'Build .NET Core Template'
        steps:
          - task: UseDotNet@2
            inputs:
              version: '5.0.x'
              performMultiLevelLookup: true

          - script: |
              dotnet pack -c $(buildConfiguration)
            workingDirectory: $(templatePath)

          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: '$(templatePath)/bin/$(buildConfiguration)'
              artifactName: 'DotNetTemplates'
              FileCopyOptions: '**/*.nupkg'

  - ${{ if eq(variables['System.TeamProject'], 'devdiv') }}:
    - stage: signing
      displayName: Signing
      dependsOn: [ 'buildsdk', 'buildtemplate' ]
      jobs:
        - template: sign-artifacts/jobs/v2.yml@internal-templates
          parameters:
            codeSignOverride: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
