trigger:
  - main
  - refs/tags/*

pr:
  - main

pool:
  vmImage: 'windows-2019'

variables:
  buildConfiguration: 'Release'
  netSdkPath: 'sdk/dotnet'
  netSdkSolution: '$(netSdkPath)/Datasync.Framework.sln'
  BASE_VERSION: 5.0.0
  PREVIEW_LABEL: 'preview'
  BUILD_NUMBER: $[counter(format('{0}_{1}_{2}', variables['BASE_VERSION'], variables['PREVIEW_LABEL'], variables['Build.SourceBranch']), 1)]
  NUGET_VERSION: $[format('{0}-{1}.{2}', variables['BASE_VERSION'], variables['PREVIEW_LABEL'], variables['BUILD_NUMBER'])]

resources:
  repositories:
    - repository: internal-templates
      type: github
      name: xamarin/yaml-templates
      endpoint: xamarin

stages:
  - stage: build
    displayName: Build SDK
    jobs:
      - job: buildnetsdk
        displayName: Build .NET SDK
        steps:
          - task: UseDotNet@2
            inputs:
              version: '5.0.x'
              performMultiLevelLookup: true

          - task: NuGetToolInstaller@1
            inputs:
              checkLatest: true

          - pwsh: |
              $pr = "pr." + $env:SYSTEM_PULLREQUEST_PULLREQUESTNUMBER
              $nuget = $env:BASE_VERSION + "-" + $pr + "." + $env:BUILD_NUMBER
              Write-Host "Preview label: $pr"
              Write-Host "NuGet version: $nuget"
              Write-Host "##vso[task.setvariable variable=PREVIEW_LABEL]$pr"
              Write-Host "##vso[task.setvariable variable=NUGET_VERSION]$nuget"
            displayName: Override version for PRs
            condition: eq(variables['Build.Reason'], 'PullRequest')

          - pwsh: |
              $tagVersion = $env:BUILD_SOURCEBRANCHNAME
              Write-Host "Tag version: $tagVersion"
              Write-Host "##vso[task.setvariable variable=NUGET_VERSION]$tagVersion"
            displayName: Override version for tags
            condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')

          - pwsh: |
              Write-Host "##vso[build.updatebuildnumber]$env:NUGET_VERSION"
            displayName: Update the build number with a more readable one 

          - task: MSBuild@1
            displayName: 'Build SDK'
            inputs:
              configuration: $(buildConfiguration)
              solution: $(netSdkSolution)
              msBuildArguments: '/nologo /t:Restore;Build;Pack /p:PackageVersion=$(NUGET_VERSION) /p:Version=$(BASE_VERSION) /bl /clp:DisableConsoleColor;Verbosity:normal;PerformanceSummary /fl'

          - pwsh: |
              Copy-Item -Verbose -Path '$(netSdkPath/src/Microsoft.*/bin/$(buildConfiguration)' -Include '$(buildArtifacts)' -Destination '$(Build.ArtifactStagingDirectory)' -Recurse
            displayName: Consolidate build artifacts

          - task: VSTest@2
            displayName: 'Run Unit Tests'
            inputs:
              testAssemblyVer2: |
                **\Microsoft.*.Test.dll
                !**\obj\**
                !**\bin\**\ref\**
              searchFolder: $(netSdkPath)
              codeCoverageEnabled: true
              diagnosticsEnabled: true
              runTestsInIsolation: true
              configuration: $(buildConfiguration)

          - template: .ci/publish.yml
            parameters:
              directory: '$(netSdkPath)/Microsoft.*/bin/$(buildConfiguration)'

      - job: buildnettemplate
        displayName: Build .NET Core Template
        steps:
          - task: UseDotNet@2
            inputs:
              version: '5.0.x'
              performMultiLevelLookup: true

          - pwsh: |
              $pr = "pr." + $env:SYSTEM_PULLREQUEST_PULLREQUESTNUMBER
              $nuget = $env:BASE_VERSION + "-" + $pr + "." + $env:BUILD_NUMBER
              Write-Host "Preview label: $pr"
              Write-Host "NuGet version: $nuget"
              Write-Host "##vso[task.setvariable variable=PREVIEW_LABEL]$pr"
              Write-Host "##vso[task.setvariable variable=NUGET_VERSION]$nuget"
            displayName: Override version for PRs
            condition: eq(variables['Build.Reason'], 'PullRequest')
            
          - pwsh: |
              $tagVersion = $env:BUILD_SOURCEBRANCHNAME
              Write-Host "Tag version: $tagVersion"
              Write-Host "##vso[task.setvariable variable=NUGET_VERSION]$tagVersion"
            displayName: Override version for tags
            condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')

          - pwsh: |
              Write-Host "##vso[build.updatebuildnumber]$env:NUGET_VERSION"
            displayName: Update the build number with a more readable one

          - pwsh: |
              dotnet pack DatasyncTemplates.csproj --configuration $(buildConfiguration) /p:PackageVersion=$(NUGET_VERSION)
            displayName: Build Template
            workingDirectory: '$(netSdkPath)/templates'

          - template: .ci/publish.yml
            parameters:
              directory: '$(netSdkPath)/templates/bin/$(buildConfiguration)'

  - stage: sign
    displayName: Sign SDK
    dependsOn: [ 'build' ]
    jobs:
      - template: sign-artifacts/jobs/v2.yml@internal-templates
        parameters:
          codeSignOverride: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
  