trigger:
  - main
  - refs/tags/*

pr:
  - main

pool:
    vmImage: 'windows-2019'

variables:
  buildConfiguration: 'Release'
  sdkDirectory: 'sdk/dotnet'
  sdkSolution: 'sdk/dotnet/Datasync.Framework.sln'
  BASE_VERSION: 5.0.0
  PREVIEW_LABEL: 'preview'
  BUILD_NUMBER: $[counter(format('{0}_{1}_{2}', variables['BASE_VERSION'], variables['PREVIEW_LABEL'], variables['Build.SourceBranch']), 1)]
  NUGET_VERSION: $[format('{0}-{1}.{2}', variables['BASE_VERSION'], variables['PREVIEW_LABEL'], variables['BUILD_NUMBER'])]

jobs:
  - job: buildsdk
    displayName: 'Build .NET SDK'
    steps:
      - task: UseDotNet@2
        displayName: 'Setup .NET Core SDK'
        inputs:
          version: '5.0.x'
          performMultiLevelLookup: true

      - task: MSBuild@1
        displayName: 'Restore packages'
        inputs:
          solution: $(sdkSolution)
          configuration: $(buildConfiguration)
          msbuildArguments: '/t:restore'

      - task: MSBuild@1
        displayName: 'Build SDK'
        inputs:
          solution: $(sdkSolution)
          configuration: $(buildConfiguration)
          msbuildArguments: '/t:build /p:PackageVersion=$(NUGET_VERSION)'
          
      - task: DotNetCoreCLI@2
        displayName: 'Run unit tests'
        inputs:
          command: 'test'
          projects: |
            $(sdkDirectory)/test/**/*.Test.csproj
            !**/Datasync.Common.Test.csproj
          arguments: '--no-restore --no-build'
          
