name: Azure Mobile Apps .NET CI
on: [ workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Azure Mobile Apps .NET Library
    steps:
      - name: Check out current source
        uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.202'

      - name: Build Library
        run: dotnet build sdk/dotnet/AzureMobile.sln

      - name: Automated unit and integration tests
        run: dotnet test sdk/dotnet/AzureMobile.sln --collect:"XPlat Code Coverage"

      - name: Produce coverage reports
        uses: danielpalme/ReportGenerator-GitHub-Action@4.8.7
        with:
          reports: sdk/dotnet/test/**/*.cobertura.xml
          targetdir: sdk/dotnet/TestResults
          reporttypes: lcov;Html
          sourcedirs: sdk/dotnet
          verbosity: Warning

      - name: Publish coverage report to coveralls.io
        uses: coverallsapp/github-action@master
        with:
          github-token: $({ secrets.GITHUB_TOKEN })
          path-to-lcov: sdk/dotnet/TestResults/lcov.info
          base-path: sdk/dotnet

      - name: Upload Coverage Reports
        uses: actions/upload-artifact@v2
        with:
          name: coverage-reports
          path: sdk/dotnet/TestResults
