name: Build .NET Libraries

on:
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

env:
  # Stop wasting time caching packages
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable usage telemetry
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  # Don't display the logo
  DOTNET_NOLOGO: true
  # GitHub Packages Feed settings
  GITHUB_FEED: https://nuget.pkg.github.com/Azure/
  GITHUB_USERNAME: adrianhall
  GiTHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sdk/dotnet
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.301
      - 
        name: Restore
        run: dotnet restore
      - 
        name: Build Server Library
        run: dotnet build -c Release --no-restore
      - 
        name: Test Server Library
        run: dotnet test -c Release
      - 
        name: Pack Server Library
        run: dotnet pack -v normal -c Release --no-restore --include-symbols --include-source -p:PackageVersion=$GITHUB_RUN_ID

      - name: Consolidate nupkg
        run: |
          mkdir nupkg
          find src \( -iname '*.nupkg' ! -iname '*.symbols.nupkg' \) -exec cp \{\} ./nupkg \;

      - 
        name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: nupkg
          path: sdk/dotnet/nupkg/*.nupkg
          if-no-files-found: error
      
  prerelease:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
      -
        name: Download Artifacts
        uses: actions/download-artifact@v1
        with:
          name: nupkg

      - 
        name: Add Nuget Source
        run: dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Azure/index.json"

      - 
        name: Publish to GitHub Packages
        run: dotnet nuget push "./nupkg/*.nupkg" -k ${{ secrets.GITHUB_TOKEN }} -s "github" --skip-duplicate
        