name: .NET Library BUILD
on: [ workflow_dispatch ]

jobs:
  build:
    name: Azure Mobile Apps .NET Library
    runs-on: ubuntu-latest
    steps:
      - name: Check out current source
        uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.202'

      - name: Install dependencies
        run: dotnet restore sdk/dotnet/AzureMobile.sln

      - name: Build Library
        run: dotnet build --no-restore sdk/dotnet/AzureMobile.sln

      - name: Automated unit and integration tests
        run: dotnet test sdk/dotnet/AzureMobile.sln --no-restore --collect:"XPlat Code Coverage"

      - name: Produce coverage reports
        uses: danielpalme/ReportGenerator-GitHub-Action@4.8.7
        with:
          reports: sdk/dotnet/test/**/*.cobertura.xml
          targetdir: sdk/dotnet/TestResults
          reporttypes: lcov;Html
          sourcedirs: sdk/dotnet
          verbosity: Warning

      - name: Pack libraries for NuGET
        run: dotnet pack -c Release sdk/dotnet/AzureMobile.sln

      - name: Upload Coverage Reports
        uses: actions/upload-artifact@v2
        with:
          name: coverage-reports
          path: sdk/dotnet/TestResults

      - name: Upload nupkg files
        uses: actions/upload-artifact@v2
        with:
          name: nupkg-files
          path: sdk/dotnet/src/**/bin/Release/*.nupkg
